drop table if exists brand cascade;
drop table if exists category cascade;
drop table if exists product cascade;
create table brand (brand_id bigint generated by default as identity, brand_name varchar(255), primary key (brand_id));
create table category (category_id bigint generated by default as identity, category_name varchar(255), primary key (category_id));
create table product (product_id bigint generated by default as identity, brand_id bigint not null, category_id bigint not null, primary key (product_id), price integer);